name: ci-go-workflow
on: [push]

jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2   #essa action baixa os arquivos para a maquina ubuntu que configuramos acima em runs-on (sem isso a pipeline nao funcionará)
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go test
      - run: go run math.go
      
      - name: SetUp Qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yumiops13/go-test-ci-project:latest
